package kg.megacom.diplomaprojectschoolmegalab.enums;

public enum EmployeeStatus {
    DIRECTOR,
    SECRETARY,
    HEAD_TEACHER,
    CLASS_TEACHER,
    MATH_TEACHER,
    HISTORY_TEACHER,
    GEOGRAPHY_TEACHER,
    ENGLISH_TEACHER,
    RUSSIAN_TEACHER,
    KYRGYZ_TEACHER,
    BIOLOGY_TEACHER,
    CHEMISTRY_TEACHER,
    PHYSICS_TEACHER,
    LITERATURE_TEACHER,
    IT_TEACHER,
    MUSIC_TEACHER,
    ART_TEACHER,
    PHYSICAL_TEACHER,
    TECHNOLOGY_TEACHER
}
